apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthlink-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthlink-frontend
  template:
    metadata:
      labels:
        app: healthlink-frontend
    spec:
      containers:
      - name: healthlink-frontend
        image: omardibba/healthlink-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi